### ISSUE TITLE
the "Login" button" is styled differently from the "Share" button

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jblast#46]
per @ihh

**Comment by enuggetry** [comment]
this is probably okay, as it is functionally different from the share button.  It wasn't intended to mimic the style.

**Comment by ihh** [comment]
They're part of the same toolbar and they should have a consistent style! The share button has square corners, a beveled border, a margin, and a blue coloring that is consistent with the toolbar. The login button has rounded corners, no border, and a gray background. This stuff matters!
<img width="421" alt="screen shot 2017-05-25 at 7 13 13 pm" src="https://cloud.githubusercontent.com/assets/54113/26478025/555443ce-417e-11e7-8e0f-1951e190fe58.png">

**Comment by enuggetry** [comment]
My own observation is that share buttons are not commonly coupled and styled with the user/login panel.
By design, it was intended to be a very compact panel.
But, of course, this is highly subjective.

Side note: the more common convention for share icon these days is:
![share2](https://cloud.githubusercontent.com/assets/10053377/26479264/bbbf7162-4186-11e7-8007-9da35b45c1a5.png)

**Comment by ihh** [comment]
Some degree of subjectivity doesn't mean there aren't fundamental UI design principles to pay attention to. For example, consider [these guidelines for Mac OS toolbars](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/ToolbarIcons.html). Note the quote (bold in original): <b>Make toolbar items distinct, yet harmonious.</b>

Or see [this usability page](https://www.usability.gov/what-and-why/user-interface-design.html) with relevant quotes "Create consistency and use common UI elements" and "Strategically use color and texture".

<i>"Share buttons are not commonly coupled and styled with the user/login panel."</i> Right: in pages with plenty of room, share buttons usually go down with the content, while login buttons are up near the navigation menu. But I don't see how we would do that here?

In any case, I fully support changing the share icon from the "link" icon (which nowadays is mostly used in WYSIWYG text editors) to the more common share icon that you posted above.

I also think we should take this opportunity (since we are adding more to what I agree is by design a compact panel) to trim both the share & login buttons down to icons (which should be harmoniously colored with the toolbar, i.e. white on blue) and move the text into tooltips.

**Comment by enuggetry** [comment]
OK. Makes sense.   However,  if the user is logged in,  I currently show
the username.
Hide or show the username?

**Comment by ihh** [comment]
i'm agnostic on that - i would just say that if we show it, we should probably avoid any borders, margins, or obvious divs altogether, and just have the text directly on the toolbar, like the menu titles ("Genome", "Track", "View"...) though in a smaller font like the "Share" text currently is.
